# iOS项目专用配置文件
workflows:
  ios-production:
    name: iOS Production Build
    environment:
      # ✅ 关键修复：显式声明项目类型
      project_type: ios
      
      # ⚙️ Xcode配置
      xcode: latest
      cocoapods: default
      node: 18.0.0
      
      # 🔠 中文路径强制修复
      vars:
        LANG: "en_US.UTF-8"
        LC_ALL: "en_US.UTF-8"
    
    # 📁 精确项目路径配置
    ios:
      project: "ios/Runner.xcodeproj"  # 🚨 替换为实际项目路径
      scheme: "Runner"                 # 🚨 替换为实际scheme名
    
    scripts:
      # 📚 依赖安装
      - cd ios
      - pod install
      
      # 🔨 签名与构建
      - xcodebuild build -project Runner.xcodeproj -scheme Runner -sdk iphoneos
      - xcodebuild archive -project Runner.xcodeproj -scheme Runner -archivePath build/Runner.xcarchive
      - xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build
    
    # 📦 生成IPA文件
    artifacts:
      - build/*.ipa
      
    # 📲 发布到App Store Connect
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        apple_id: $APPLE_DEVELOPER_ACCOUNT