#!/bin/bash
# ===== 1. 获取上传凭证 =====
RESPONSE=$(curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $CM_API_KEY" \
  -d '{
    "appId": "'$CM_APP_ID'",
    "workflowId": "'$CM_WORKFLOW_ID'",
    "branch": "main",
    "environment": { 
      "variables": {
        "IOS_SIGNING_TYPE": "development"
      }
    }
  }' \
  "https://api.codemagic.io/builds"
)

# ===== 2. 提取构建ID =====
BUILD_ID=$(echo $RESPONSE | jq -r '.buildId')
echo "构建已启动，ID: $BUILD_ID"

# ===== 3. 上传IPA文件（无需配置） =====
curl -X POST \
  -H "Authorization: Bearer $CM_API_KEY" \
  -F "file=@/path/to/YourApp.ipa" \
  "https://api.codemagic.io/builds/$BUILD_ID/artifacts"