# codemagic.yaml - iOS配置参考
workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      node: 18
    scripts:
      - name: 安装依赖
        script: |
          cd ios
          pod install
          cd ..
      - name: 构建IPA
        script: |
          flutter build ipa --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID